### ISSUE TITLE
Only 2020.1.12 version available through Plugins configuration

### ISSUE THREAD

**Issue by tedyoung** [b333vv/metricstree#38]
I'm using IntelliJ IDEA 2022.3.1 and the (old?) 2020.1.12 version is the only one that comes up in the Plugins directory, because the latest (2023.1.0) is only marked compatible through 2021.3.3, which is quite old, whereas the 2020.1.12 is compatible with 2019.3+ (which is everything since then). This might be very confusing to people (like me), is there a way to fix this?

Ideally, releasing a version compatible with 2022.3.1? Happy to test that.

**Comment by b333vv** [comment]
Thank you for your response. I'll get to it soon.
9 янв. 2023 г., 02:33 +0300, b333vv/metricstree ***@***.***>, писал:
>
> I'm using IntelliJ IDEA 2022.3.1 and the (old?) 2020.1.12 version is the only one that comes up in the Plugins directory, because the latest (2023.1.0) is only marked compatible through 2021.3.3, which is quite old, whereas the 2020.1.12 is compatible with 2019.3+ (which is everything since then). This might be very confusing to people (like me), is there a way to fix this?
>
> Ideally, releasing a version compatible with 2022.3.1? Happy to test that.

**Comment by b333vv** [comment]
check version 2023.2.2
