### ISSUE TITLE
Feature Request: Export project metrics as html

### ISSUE THREAD

**Issue by Xiaoven** [b333vv/metricstree#43]
**Issue: Large XML File for Project Metrics**

I want to highlight a concern with our current project metrics export. The plugin generates a single, oversized XML file, over 80MB in size. This causes significant issues when trying to access and review the data.

**Problem: Overheating and Long Load Times**

Opening this large XML file in a web browser on my local machine leads to severe overheating, with the cooling fans operating at full speed. Unfortunately, even after waiting for an extended period, the file often fails to load.

**Suggestion: Follow Jacoco's Export Format**

I recommend considering an alternative approach similar to Jacoco's export format. It splits content into HTML files and associated resources. This change would greatly improve the user experience, making it easier to load and navigate through the data.

**Comment by b333vv** [comment]
Sorry, missed your message. I'll get to it one of these days.

**Comment by b333vv** [comment]
In version 2023.3.0 I added the ability to export package metrics and method metrics separately. Please check if this will solve your problem.
