### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by obprs-iscte** [b333vv/metricstree#6]
Hello,

I'm currently using IntelliJ IDEA 2021.3.2.

The tab "Project Metrics" tab keeps displaying "Nothing to show" and after clicking on "Calculate Project Metrics" it shows the following error:
![error](https://user-images.githubusercontent.com/100206299/161604940-ffe13db6-628b-4f19-9a48-529eac2c312d.jpg)

The Log Console:
![image](https://user-images.githubusercontent.com/100206299/161605418-abadb40e-026a-445e-970c-8ecf5ccf443f.png)
It can only calculate metrics for classes.

Could you help me? 
Thank you very much.

**Comment by b333vv** [comment]
Hello,

this issue has probably been fixed in version 2022.1.1. please check it.

**Comment by obprs-iscte** [comment]
Hello,

I would like to try it out but the version 2022.1.1 is not available yet at the IntelliJ Marketplace.

**Comment by obprs-iscte** [comment]
Thank you very much! I'll give you feedback when it's available.

**Comment by b333vv** [comment]
Ok, thank you!

**Comment by obprs-iscte** [comment]
It works! Thank you! :)
