### ISSUE TITLE
Miscalculation of LOC Metric

### ISSUE THREAD

**Issue by furkanozbay** [b333vv/metricstree#7]
I am using MetricsTree to analyze this project: https://github.com/android/architecture-samples/tree/todo-mvp

When I analyzed the openTask method of TaskDetailPresenter.java class, I noticed LOC metric seems wrong. I think it is caused from anonymous objects.

The results of openTask metrics I get is
![image](https://user-images.githubusercontent.com/8355795/169720382-848b8e6f-4ff2-497d-9c79-c94ff8ebf0ed.png)

I expect the LOC would be higher than this, around 30.

When I calculate LOC metric with different plugin it shows LOC as 30
![image](https://user-images.githubusercontent.com/8355795/169735410-56c26f29-9df9-4ee6-be79-93babf76622b.png)

**Comment by b333vv** [comment]
Fixed in version 2022.1.2, please check it.

**Comment by furkanozbay** [comment]
It is fixed, thanks :handshake:
